package iot.lviv.ua.educationproject;

/**
 * Created by Volodymyr on 07.05.2018.
 */

public enum TypeOfClass {
    MATHEMATICAL_ANALYSIS_LECTURE, MATHEMATICAL_ANALYSIS_PRACTICE, ENGLISH_PRACTICE,
    ELECTROTECHNICS_AND_ELECTRONICS_LECTURE, ELECTROTECHNICS_AND_ELECTRONICS_LABORATORY, PHYSICS_LECTURE,
    PHYSICS_PRACTICE, PHYSICS_LABORATORY, PROGRAMMING_PART_2_LECTURE, PROGRAMMING_PART_2_LABORATORY,
    DISCRET_MATH_LECTURE, DISCRET_MATH_PRACTICE, UKRAINIAN_PRACTICE
}
